version: 2

sources:
  - name: raw
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    loader: snowflake
    description: >
      Raw tables loaded from source systems via ingestion pipelines.
      These tables are not created by dbt.

    tables:
      - name: NATION
        description: Raw NATION table
      